### ISSUE TITLE
v3.2.2 on PS 1.6.1.18 creates 2-home in sitemap

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/gsitemap#100] opened 2018-12-31 13:28 UTC
i've 2 languages configured in my ps 1.6.1.18 and i noticed in the sitemap 2strange 404 urls, one per language:

`<url>
<loc><![CDATA[https://www.angelovintage.com/it/2-home]]></loc>
<priority>0.8</priority>
<lastmod>2017-01-16T08:59:54+01:00</lastmod>
<changefreq>daily</changefreq>
</url>`

`<url>
<loc><![CDATA[https://www.angelovintage.com/en/2-home]]></loc>
<priority>0.8</priority>
<lastmod>2017-01-16T08:59:54+01:00</lastmod>
<changefreq>daily</changefreq>
</url>`

i don't have any category ID=2
![image](https://user-images.githubusercontent.com/16102074/50561102-db7f5c80-0d07-11e9-89e0-ef6b09ec2b2e.png)

I don't have idea how 2-home urls are generated and i dont' have fouind a fix.

thanks

**Comment by khouloudbelguith** [comment] 2019-01-07 07:56
Hi @HartLarsson,

Your issue is fixed with this PR: https://github.com/PrestaShop/gsitemap/pull/61.
Thanks!

**Comment by khouloudbelguith** [comment] 2019-01-07 07:56
Duplicate of https://github.com/PrestaShop/gsitemap/issues/59

**Closed by khouloudbelguith** 2019-01-07 07:56 UTC

**Comment by HartLarsson** [comment] 2019-01-07 18:50
i checked the version 3.2.2 (the latest available for 1.6.1.x and the problem opersist. 
Please apply the patch to the 1.6.x branch/tag too

thanks

**Comment by MathiasReker** [comment] 2019-01-07 18:51
You can patch it buy replace the line from this pr: #59

**Comment by HartLarsson** [comment] 2019-01-07 18:55
I will do that way ;) but would be nice to move the fix to next version from 3.2.2 to 3.2.3 for 1.6 so people can get the fixed version in easy way ;)

thanks

**Comment by MathiasReker** [comment] 2019-01-07 18:56
I don't think gsitemap will be supported anymore for 1.6, sorry.

**Comment by HartLarsson** [comment] 2019-01-08 19:44
anyway i fixed the 2-home bug adapting your code:

`		$categories_id = Db::getInstance()->ExecuteS(
			'SELECT c.id_category FROM `'._DB_PREFIX_.'category` c
				INNER JOIN `'._DB_PREFIX_.'category_shop` cs ON c.`id_category` = cs.`id_category`
				WHERE c.`id_category` >= '.intval($id_category).' AND c.`active` = 1 AND c.`id_category` != 1 AND c.id_category != ' . (int) Configuration::get('PS_HOME_CATEGORY') . ' AND c.id_parent > 0 AND c.`id_category` > 0 AND cs.`id_shop` = '.(int)$this->context->shop->id.' ORDER BY c.`id_category` ASC'
				
		);`
